Checkpointer
stanford-crfm/levanter pull request #43
Opened 2022-11-01 23:17 UTC by dlwh

here's a cut at checkpointing we outlined last week:

It saves a checkpoint at least every `save_interval` seconds (default 6 hours), and supports saving checkpoints based on a number of steps (which can vary over the course of the run, a la Mistral). the "save_interval" triggered checkpoints only keep the most recent.

I'm a bad person and didn't really write unit tests for this (I guess I could do DI for the checkpointer...) I'll try to write some tonight I think.

2022-11-01 23:19 UTC, dlwh commented on src/levanter/config.py
> +    def encode_timedelta(td: timedelta):
i can't believe there's no builtin or easily pip installable library for this?

2022-11-02 16:21 UTC, yifanmai requested changes

2022-11-02 16:48 UTC, dlwh commented on src/levanter/checkpoint.py
> +        self.on_step(info)
oops, thanks. i added that late in the game

2022-11-02 16:50 UTC, dlwh commented on src/levanter/checkpoint.py
> +    def __init__(self, path: str, save_interval: datetime.timedelta, keep: Sequence[CheckpointInterval]):
it's not so much default_path as base_path. I'll do that?

2022-11-02 16:52 UTC, yifanmai commented on src/levanter/checkpoint.py
> +    def __init__(self, path: str, save_interval: datetime.timedelta, keep: Sequence[CheckpointInterval]):
`base_path` sounds good.

2022-11-02 16:56 UTC, yifanmai commented on src/levanter/checkpoint.py
> +    def __call__(self, info, force: bool = False):
I think a method should work as a callable i.e. `engine.add_hook(checkpointer.some_method, every=1)` should still work

2022-11-02 17:01 UTC, dlwh commented on src/levanter/config.py
> +        import pytimeparse
i don't remember why i did this

2022-11-02 17:03 UTC, dlwh commented on src/levanter/config.py
> +    def create(self, run_name) -> Checkpointer:
i saw this as a builder pattern where having a build/create method on the builder/config is pretty normal?

2022-11-02 17:24 UTC, dlwh commented
yeah i realized that after i replied... I'm still noobish at python
sometimes

On Wed, Nov 2, 2022 at 9:56 AM Yifan Mai ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/levanter/checkpoint.py
> <https://github.com/stanford-crfm/levanter/pull/43#discussion_r1012056836>
> :
>
> > +        self._keep_stack = list(keep)
> +        self._last_save_time = datetime.datetime.now()
> +        self._last_save_step = 0
> +        self._last_temporary_checkpoint = None
> +
> +    def load_checkpoint(self, model, training_state, path: Optional[str] = None, *, discover_latest: bool = True):
> +        if path is None:
> +            path = self.path
> +        return load_checkpoint(model, training_state, path, discover_latest=discover_latest)
> +
> +    def load_model(self, model, path: Optional[str] = None, *, discover_latest: bool = True):
> +        if path is None:
> +            path = self.path
> +        return load_checkpoint(model, None, path, discover_latest=discover_latest)
> +
> +    def __call__(self, info, force: bool = False):
>
> I think a method should work as a callable i.e. engine.add_hook(checkpointer.some_method,
> every=1) should still work
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/stanford-crfm/levanter/pull/43#discussion_r1012056836>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAACLIKW25ZAB4J5CQYYOYLWGKMMNANCNFSM6AAAAAARUQ4FSI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-02 19:00 UTC, merged

2022-11-02 19:10 UTC, dlwh commented on src/levanter/config.py
> +    def create(self, run_name) -> Checkpointer:
(i left this as-is for now. if you feel strongly I'll change, but I prefer to keep the run_name-based knot-tying in the config classes)

2022-11-02 22:47 UTC, yifanmai commented on src/levanter/config.py
> +    def create(self, run_name) -> Checkpointer:
Sounds good to me.